const courses= [
  {
    _id: "p1",
    title: "HTML & CSS Basics",
    description: "Learn the building blocks of web development with HTML and CSS.",
    category: "Web",
    level: "basic",
    duration: "3h",
    modules: 12,
    popular: true,
    thumbnail: "/thumbnails/html-css.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p2",
    title: "JavaScript Fundamentals",
    description: "Understand the core concepts of JavaScript, including variables, functions, and loops.",
    category: "Javascript",
    level: "basic",
    duration: "5h",
    modules: 15,
    popular: false,
    thumbnail: "/thumbnails/js-fundamentals.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p3",
    title: "Advanced JavaScript Concepts",
    description: "Dive deeper into closures, promises, async/await, and advanced ES6+ features.",
    category: "Javascript",
    level: "advance",
    duration: "7h",
    modules: 18,
    popular: true,
    thumbnail: "/thumbnails/advanced-js.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p4",
    title: "Responsive Web Design",
    description: "Master responsive layouts using Flexbox, Grid, and media queries.",
    category: "Web",
    level: "advance",
    duration: "6h",
    modules: 16,
    popular: false,
    thumbnail: "/thumbnails/responsive-design.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p5",
    title: "C Programming Basics",
    description: "Introduction to C programming language with variables, loops, and functions.",
    category: "C",
    level: "basic",
    duration: "4h",
    modules: 14,
    popular: true,
    thumbnail: "/thumbnails/c-basics.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p6",
    title: "Pointers and Memory in C",
    description: "Deep dive into pointers, memory allocation, and data structures in C.",
    category: "C",
    level: "advance",
    duration: "8h",
    modules: 20,
    popular: false,
    thumbnail: "/thumbnails/c-pointers.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p7",
    title: "Python for Beginners",
    description: "Get started with Python, covering syntax, variables, and basic problem solving.",
    category: "Python",
    level: "basic",
    duration: "5h",
    modules: 15,
    popular: true,
    thumbnail: "/thumbnails/python-basics.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p8",
    title: "Python OOP Mastery",
    description: "Learn Object-Oriented Programming in Python with classes, inheritance, and polymorphism.",
    category: "Python",
    level: "advance",
    duration: "7h",
    modules: 18,
    popular: false,
    thumbnail: "/thumbnails/python-oop.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p9",
    title: "Ruby Essentials",
    description: "Start coding in Ruby with basic syntax, loops, and data structures.",
    category: "Ruby",
    level: "basic",
    duration: "4h",
    modules: 12,
    popular: true,
    thumbnail: "/thumbnails/ruby-essentials.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p10",
    title: "Ruby on Rails Advanced",
    description: "Build full-stack applications with Ruby on Rails, including REST APIs.",
    category: "Ruby",
    level: "advance",
    duration: "10h",
    modules: 22,
    popular: false,
    thumbnail: "/thumbnails/ruby-rails.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p11",
    title: "Web Accessibility Basics",
    description: "Learn how to make your websites accessible for everyone.",
    category: "Web",
    level: "basic",
    duration: "3h",
    modules: 10,
    popular: true,
    thumbnail: "/thumbnails/web-accessibility.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p12",
    title: "Web Performance Optimization",
    description: "Techniques to speed up your website and improve user experience.",
    category: "Web",
    level: "advance",
    duration: "5h",
    modules: 14,
    popular: false,
    thumbnail: "/thumbnails/web-performance.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p13",
    title: "JavaScript DOM Manipulation",
    description: "Manipulate the DOM effectively using vanilla JavaScript.",
    category: "Javascript",
    level: "basic",
    duration: "4h",
    modules: 13,
    popular: true,
    thumbnail: "/thumbnails/js-dom.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p14",
    title: "JavaScript Async Programming",
    description: "Master callbacks, promises, and async/await in JavaScript.",
    category: "Javascript",
    level: "advance",
    duration: "6h",
    modules: 16,
    popular: false,
    thumbnail: "/thumbnails/js-async.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p15",
    title: "C Control Structures",
    description: "Learn conditional statements, loops, and switch cases in C.",
    category: "C",
    level: "basic",
    duration: "3h",
    modules: 11,
    popular: true,
    thumbnail: "/thumbnails/c-control.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p16",
    title: "Data Structures in C",
    description: "Understand arrays, linked lists, stacks, and queues in C.",
    category: "C",
    level: "advance",
    duration: "7h",
    modules: 19,
    popular: false,
    thumbnail: "/thumbnails/c-data-structures.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p17",
    title: "Python Data Analysis",
    description: "Learn to analyze and visualize data with Python libraries.",
    category: "Python",
    level: "advance",
    duration: "8h",
    modules: 20,
    popular: true,
    thumbnail: "/thumbnails/python-data-analysis.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p18",
    title: "Python File Handling",
    description: "Read, write, and manipulate files in Python.",
    category: "Python",
    level: "basic",
    duration: "3h",
    modules: 10,
    popular: false,
    thumbnail: "/thumbnails/python-file.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p19",
    title: "Ruby Gems & Libraries",
    description: "Explore Ruby's package ecosystem and how to use gems effectively.",
    category: "Ruby",
    level: "advance",
    duration: "6h",
    modules: 15,
    popular: true,
    thumbnail: "/thumbnails/ruby-gems.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p20",
    title: "Ruby Control Flow",
    description: "Learn conditional statements, loops, and iterators in Ruby.",
    category: "Ruby",
    level: "basic",
    duration: "3h",
    modules: 11,
    popular: false,
    thumbnail: "/thumbnails/ruby-control.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p21",
    title: "CSS Animations",
    description: "Bring websites to life with animations and transitions.",
    category: "Web",
    level: "advance",
    duration: "5h",
    modules: 14,
    popular: true,
    thumbnail: "/thumbnails/css-animations.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p22",
    title: "Semantic HTML",
    description: "Learn the importance of semantic HTML tags for SEO and accessibility.",
    category: "Web",
    level: "basic",
    duration: "2h",
    modules: 8,
    popular: false,
    thumbnail: "/thumbnails/semantic-html.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p23",
    title: "JavaScript ES6 Features",
    description: "Understand modern JavaScript features like let, const, arrow functions, and classes.",
    category: "Javascript",
    level: "basic",
    duration: "4h",
    modules: 12,
    popular: true,
    thumbnail: "/thumbnails/js-es6.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p24",
    title: "JavaScript Design Patterns",
    description: "Implement popular design patterns in JavaScript for scalable apps.",
    category: "Javascript",
    level: "advance",
    duration: "7h",
    modules: 18,
    popular: false,
    thumbnail: "/thumbnails/js-design-patterns.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p25",
    title: "C Functions & Recursion",
    description: "Learn modular programming with functions and recursion in C.",
    category: "C",
    level: "basic",
    duration: "3h",
    modules: 10,
    popular: true,
    thumbnail: "/thumbnails/c-functions.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p26",
    title: "C File Handling",
    description: "Work with file I/O in C programs effectively.",
    category: "C",
    level: "advance",
    duration: "6h",
    modules: 15,
    popular: false,
    thumbnail: "/thumbnails/c-file.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p27",
    title: "Python Web Development",
    description: "Build web apps with Python using Flask and Django.",
    category: "Python",
    level: "advance",
    duration: "9h",
    modules: 22,
    popular: true,
    thumbnail: "/thumbnails/python-web.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p28",
    title: "Python Basics",
    description: "Introduction to Python variables, operators, and loops.",
    category: "Python",
    level: "basic",
    duration: "4h",
    modules: 12,
    popular: false,
    thumbnail: "/thumbnails/python-basics-2.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p29",
    title: "Ruby OOP",
    description: "Understand classes, objects, and inheritance in Ruby.",
    category: "Ruby",
    level: "basic",
    duration: "4h",
    modules: 13,
    popular: true,
    thumbnail: "/thumbnails/ruby-oop.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p30",
    title: "Ruby Metaprogramming",
    description: "Advanced Ruby concepts like reflection and dynamic method creation.",
    category: "Ruby",
    level: "advance",
    duration: "8h",
    modules: 20,
    popular: false,
    thumbnail: "/thumbnails/ruby-meta.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: "p31",
    title: "Advanced JavaScript Tutorials",
    description: "Automate workflows and processes with advanced Python scripting.",
    category: "JS",
    level: "advance",
    duration: "9h",
    modules: 21,
    popular: false,
    thumbnail: "/thumbnails/advanced-js-tutorials.png",
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
];

export default courses;
